---
- hosts: 172.31.41.128
  become: True
  tasks:
    - name: Install apache
      yum:
        name: httpd
        state: present
    - name: copy html file
      copy: 
        src: index.html
        dest: /var/www/html
    - name: start apache server
      service:
        name: httpd
        state: started
        enabled: true